"""
app/schemas/voice.py

Pydantic schemas for the voice assistant feature.
Mirrors the style of your other schema files (prediction.py, simple_crop_schema.py)
— adjust field names/base classes if your convention differs.
"""

from pydantic import BaseModel
from typing import Optional


class VoiceQueryResponse(BaseModel):
    """
    Returned by POST /voice/query after the full STT -> intent -> TTS pipeline.
    """
    transcribed_text: str          # what Whisper heard
    detected_language: str         # language code Whisper detected (e.g. "ta", "hi", "en")
    response_text: str             # the text answer generated by the routed feature
    audio_response_path: str       # path/URL to the generated gTTS audio reply
    intent: Optional[str] = None   # which internal feature handled it (e.g. "crop", "disease", "market")


class VoiceQueryError(BaseModel):
    detail: str