"""
app/schemas/voice.py

Pydantic schemas for the voice assistant feature.
Mirrors the style of your other schema files (prediction.py, simple_crop_schema.py)
— adjust field names/base classes if your convention differs.
"""

from pydantic import BaseModel
from typing import Optional

from app.schemas.prediction import CropOutput, DiseaseOutput, WeedPestOutput


class VoiceQueryResponse(BaseModel):
    """
    Returned by POST /voice/query after the full STT -> intent -> TTS pipeline.
    """
    transcribed_text: str          # what Whisper heard
    detected_language: str         # language code Whisper detected (e.g. "ta", "hi", "en")
    response_text: str             # the text answer generated by the routed feature
    audio_response_path: str       # path/URL to the generated gTTS audio reply
    intent: Optional[str] = None   # which internal feature handled it (e.g. "crop", "disease", "market")


class ModelResult(BaseModel):
    """
    One entry in `results`. Exactly mirrors CROP_FIELDS in the frontend repo src/api.js
    (mirroring CropOutput), with the extra discriminator `model` so the
    frontend's ModelCard knows which card to render. Disease and pest results
    reuse the same object with only the subset of fields they actually set.
    """
    model: str                                        # "crop" | "disease" | "pest"
    predicted_crop: Optional[str] = None              # crop only
    predicted_class: Optional[str] = None             # disease / pest (and crop keep null)
    confidence: float
    confidence_label: str                             # "high" | "medium" | "low"
    soil_source: Optional[str] = None                 # crop only
    weather_source: Optional[str] = None              # crop only
    location: Optional[str] = None                    # crop only
    warning: Optional[str] = None                     # crop only
    data_resolution: Optional[str] = None             # crop only: district|state|fallback|manual
    input_confidence: Optional[str] = None            # crop only: high|medium|low
    data_quality_note: Optional[str] = None           # crop only


class UnifiedVoiceResponse(BaseModel):
    """
    Final /voice/query response. Shape is the exact contract the frontend
    repo's src/api.js real mode consumes:

      - text_response       -> summary shown in the results screen
                              (frontend reads text_response || response)
      - results[]           -> one ModelResult per model that ran, so the
                              frontend's per-model cards (incl. the
                              data_resolution badge + data_quality_note)
                              render with zero frontend changes
      - audio_url           -> absolute URL the TTS play button can fetch

    crop_result / disease_result / pest_result are the schema-typed siblings
    (CropOutput / DiseaseOutput / WeedPestOutput), each are null when that
    model did not run.
    """
    intent: Optional[str] = None
    transcribed_text: str = ""
    detected_language: str = "en"
    language_probability: Optional[float] = None
    text_response: str = ""                          # summary (frontend source of truth)
    response_text: str = ""                          # legacy alias
    audio_url: Optional[str] = None                  # absolute URL (frontend)
    audio_response_path: Optional[str] = None        # legacy relative path
    results: list[ModelResult] = []
    crop_result: Optional[CropOutput] = None
    disease_result: Optional[DiseaseOutput] = None
    pest_result: Optional[WeedPestOutput] = None


class VoiceQueryError(BaseModel):
    detail: str