#!/usr/bin/env bash
#
# gen_android_keystore.sh — create the Valam AI Android *upload* keystore and the
# git-ignored key.properties that the Gradle release build reads.
#
# Run this ONCE, on the machine that will sign releases. See
# playstore/APP_SIGNING.md for the full Play App Signing explanation.
#
# Design choices:
#   * The keystore is written OUTSIDE the git repo (default ~/valam-keystore) and
#     the script refuses to run if you point it inside the repo.
#   * The password is never echoed and never passed on the command line.
#   * key.properties (created in frontend/android/) is already git-ignored.
#   * Existing keystores are never overwritten — losing this file means losing
#     the ability to update the app on Play, so it is intentionally conservative.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ALIAS="${KEY_ALIAS:-valam-upload}"
OUT_DIR="${KEYSTORE_DIR:-$HOME/valam-keystore}"
KEYSTORE="$OUT_DIR/valam-upload.jks"
KEYPROPS="$REPO_ROOT/frontend/android/key.properties"
DNAME="${KEY_DNAME:-CN=Valam AI, OU=Mobile, O=Valam AI, L=Chennai, ST=Tamil Nadu, C=IN}"

command -v keytool >/dev/null 2>&1 || {
  echo "ERROR: keytool not found. Install a JDK 17+ (e.g. 'brew install --cask temurin@17') and retry." >&2
  exit 1
}

case "$OUT_DIR" in
  "$REPO_ROOT"*)
    echo "ERROR: refusing to create the keystore inside the git repo ($REPO_ROOT)." >&2
    echo "       Set KEYSTORE_DIR to a location outside the repo, e.g. ~/valam-keystore." >&2
    exit 1
    ;;
esac

[ -f "$KEYSTORE" ] && {
  echo "ERROR: a keystore already exists at:"
  echo "         $KEYSTORE"
  echo "       Refusing to overwrite it (that would break future Play updates)."
  echo "       Move it aside first if you really want to regenerate."
  exit 1
}

echo "Creating upload keystore -> $KEYSTORE"
echo "Alias: $ALIAS"
echo
read -r -s -p "Choose a keystore password (min 12 chars): " PW; echo
read -r -s -p "Confirm password: " PW2; echo

[ "$PW" = "$PW2" ] || { echo "ERROR: passwords did not match." >&2; exit 1; }
[ "${#PW}" -ge 12 ] || { echo "ERROR: use at least 12 characters." >&2; exit 1; }

mkdir -p "$OUT_DIR"
chmod 700 "$OUT_DIR"

keytool -genkeypair -v \
  -keystore "$KEYSTORE" \
  -storetype PKCS12 \
  -alias "$ALIAS" \
  -keyalg RSA \
  -keysize 2048 \
  -validity 10000 \
  -dname "$DNAME" \
  -storepass "$PW" \
  -keypass "$PW"

chmod 600 "$KEYSTORE"

umask 077
cat > "$KEYPROPS" <<EOF
## Auto-generated by scripts/gen_android_keystore.sh — DO NOT COMMIT.
## This file is git-ignored. Back it up alongside the .jks.
storeFile=$KEYSTORE
storePassword=$PW
keyAlias=$ALIAS
keyPassword=$PW
EOF
chmod 600 "$KEYPROPS"

cat <<EOF

✅ Done.

  Keystore     : $KEYSTORE
  key.properties: $KEYPROPS

NEXT STEPS (see playstore/APP_SIGNING.md):
  1. BACK UP the keystore .jks AND these passwords somewhere safe and offline.
     If you lose them you cannot publish updates to this app listing.
  2. Enroll in Play App Signing (Play Console) and upload the first .aab signed
     with this key — Google then re-signs with the app signing key it manages.
  3. Build a release bundle:
       cd frontend && npm run build && npx cap sync android
       cd android && ./gradlew bundleRelease
     Output: frontend/android/app/build/outputs/bundle/release/app-release.aab

⚠️  Keep the password out of shell history / chat / screenshots.
EOF
